name: Tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    paths-ignore:
      - '.github/workflows/release.yml'
      - '.github/workflows/pr_checks.yml'

permissions: read-all

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    name: pre-commit
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout code
        uses: actions/checkout@v4.2.2

      - name: login to gitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          runCmd: pre-commit run -a
          imageName: ghcr.io/dodwmd/leonardo-terraform-aws-s3
          cacheFrom: ghcr.io/dodwmd/leonardo-terraform-aws-s3:latest

  test:
    needs: pre_commit
    runs-on: ubuntu-latest
    name: terraform latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4.2.2

      - name: setup latest terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: set up go
        uses: actions/setup-go@v5.1.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: test
        run: go test -v ./tests

  multi:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform-version: ['1.9.8']
    name: terraform ${{ matrix.terraform-version }}
    steps:
      - name: checkout code
        uses: actions/checkout@v4.2.2

      - name: setup terraform ${{ matrix.terraform-version }}
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.terraform-version }}
          terraform_wrapper: false

      - name: set up go
        uses: actions/setup-go@v5.1.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: test
        run: go test -v ./tests
